// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MovingHarmonicRestraint_hpp__pyplusplus_wrapper
#define MovingHarmonicRestraint_hpp__pyplusplus_wrapper

void register_MovingHarmonicRestraint_class();

#endif//MovingHarmonicRestraint_hpp__pyplusplus_wrapper
