// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "MovingHarmonicRestraint.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "movingharmonicrestraints.h"

#include <QDebug>

#include "movingharmonicrestraints.h"

SireMM::MovingHarmonicRestraint __copy__(const SireMM::MovingHarmonicRestraint &other){ return SireMM::MovingHarmonicRestraint(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

void register_MovingHarmonicRestraint_class(){

    { //::SireMM::MovingHarmonicRestraint
        typedef bp::class_< SireMM::MovingHarmonicRestraint, bp::bases< SireBase::Property > > MovingHarmonicRestraint_exposer_t;
        MovingHarmonicRestraint_exposer_t MovingHarmonicRestraint_exposer = MovingHarmonicRestraint_exposer_t( "MovingHarmonicRestraint", "This class represents a single Morse restraint between any two\natoms in a system (or between the centroids of any two groups\nof atoms in a system)\n", bp::init< >("Null constructor") );
        bp::scope MovingHarmonicRestraint_scope( MovingHarmonicRestraint_exposer );
        MovingHarmonicRestraint_exposer.def( bp::init< qint64, qint64, SireUnits::Dimension::HarmonicBondConstant const &, SireUnits::Dimension::Length const &, SireUnits::Dimension::Length const & >(( bp::arg("atom0"), bp::arg("atom1"), bp::arg("k"), bp::arg("r0"), bp::arg("r1") ), "Construct to restrain the atom at index atom to the specified position\n  using the specified force constant and flat-bottom well-width\n") );
        MovingHarmonicRestraint_exposer.def( bp::init< QList< long long > const &, QList< long long > const &, SireUnits::Dimension::HarmonicBondConstant const &, SireUnits::Dimension::Length const &, SireUnits::Dimension::Length const & >(( bp::arg("atoms0"), bp::arg("atoms1"), bp::arg("k"), bp::arg("r0"), bp::arg("r1") ), "Construct to restrain the centroid of the atoms whose indicies are\n  in atoms to the specified position using the specified force constant\n  and flat-bottom well width\n") );
        MovingHarmonicRestraint_exposer.def( bp::init< SireMM::MovingHarmonicRestraint const & >(( bp::arg("other") ), "Copy constructor") );
        { //::SireMM::MovingHarmonicRestraint::atom0
        
            typedef ::qint64 ( ::SireMM::MovingHarmonicRestraint::*atom0_function_type)(  ) const;
            atom0_function_type atom0_function_value( &::SireMM::MovingHarmonicRestraint::atom0 );
            
            MovingHarmonicRestraint_exposer.def( 
                "atom0"
                , atom0_function_value
                , bp::release_gil_policy()
                , "Return the index of the atom if this is a single-atom restraint" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::atom1
        
            typedef ::qint64 ( ::SireMM::MovingHarmonicRestraint::*atom1_function_type)(  ) const;
            atom1_function_type atom1_function_value( &::SireMM::MovingHarmonicRestraint::atom1 );
            
            MovingHarmonicRestraint_exposer.def( 
                "atom1"
                , atom1_function_value
                , bp::release_gil_policy()
                , "Return the index of the atom if this is a single-atom restraint" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::atoms0
        
            typedef ::QVector< long long > ( ::SireMM::MovingHarmonicRestraint::*atoms0_function_type)(  ) const;
            atoms0_function_type atoms0_function_value( &::SireMM::MovingHarmonicRestraint::atoms0 );
            
            MovingHarmonicRestraint_exposer.def( 
                "atoms0"
                , atoms0_function_value
                , bp::release_gil_policy()
                , "Return the indexes of the atoms whose centroid is to be restrained" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::atoms1
        
            typedef ::QVector< long long > ( ::SireMM::MovingHarmonicRestraint::*atoms1_function_type)(  ) const;
            atoms1_function_type atoms1_function_value( &::SireMM::MovingHarmonicRestraint::atoms1 );
            
            MovingHarmonicRestraint_exposer.def( 
                "atoms1"
                , atoms1_function_value
                , bp::release_gil_policy()
                , "Return the indexes of the atoms whose centroid is to be restrained" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::isAtomRestraint
        
            typedef bool ( ::SireMM::MovingHarmonicRestraint::*isAtomRestraint_function_type)(  ) const;
            isAtomRestraint_function_type isAtomRestraint_function_value( &::SireMM::MovingHarmonicRestraint::isAtomRestraint );
            
            MovingHarmonicRestraint_exposer.def( 
                "isAtomRestraint"
                , isAtomRestraint_function_value
                , bp::release_gil_policy()
                , "Return whether this is a single-atom restraint" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::isCentroidRestraint
        
            typedef bool ( ::SireMM::MovingHarmonicRestraint::*isCentroidRestraint_function_type)(  ) const;
            isCentroidRestraint_function_type isCentroidRestraint_function_value( &::SireMM::MovingHarmonicRestraint::isCentroidRestraint );
            
            MovingHarmonicRestraint_exposer.def( 
                "isCentroidRestraint"
                , isCentroidRestraint_function_value
                , bp::release_gil_policy()
                , "Return whether this restraint acts on the centroid of a group\n  of atoms" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::isNull
        
            typedef bool ( ::SireMM::MovingHarmonicRestraint::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::MovingHarmonicRestraint::isNull );
            
            MovingHarmonicRestraint_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::k
        
            typedef ::SireUnits::Dimension::HarmonicBondConstant ( ::SireMM::MovingHarmonicRestraint::*k_function_type)(  ) const;
            k_function_type k_function_value( &::SireMM::MovingHarmonicRestraint::k );
            
            MovingHarmonicRestraint_exposer.def( 
                "k"
                , k_function_value
                , bp::release_gil_policy()
                , "Return the force constant for the restraint" );
        
        }
        MovingHarmonicRestraint_exposer.def( bp::self != bp::self );
        MovingHarmonicRestraint_exposer.def( bp::self + bp::self );
        MovingHarmonicRestraint_exposer.def( bp::self + bp::other< SireMM::MovingHarmonicRestraints >() );
        { //::SireMM::MovingHarmonicRestraint::operator=
        
            typedef ::SireMM::MovingHarmonicRestraint & ( ::SireMM::MovingHarmonicRestraint::*assign_function_type)( ::SireMM::MovingHarmonicRestraint const & ) ;
            assign_function_type assign_function_value( &::SireMM::MovingHarmonicRestraint::operator= );
            
            MovingHarmonicRestraint_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        MovingHarmonicRestraint_exposer.def( bp::self == bp::self );
        { //::SireMM::MovingHarmonicRestraint::r0
        
            typedef ::SireUnits::Dimension::Length ( ::SireMM::MovingHarmonicRestraint::*r0_function_type)(  ) const;
            r0_function_type r0_function_value( &::SireMM::MovingHarmonicRestraint::r0 );
            
            MovingHarmonicRestraint_exposer.def( 
                "r0"
                , r0_function_value
                , bp::release_gil_policy()
                , "Return the width of the harmonic MovingHarmonic." );
        
        }
        { //::SireMM::MovingHarmonicRestraint::r1
        
            typedef ::SireUnits::Dimension::Length ( ::SireMM::MovingHarmonicRestraint::*r1_function_type)(  ) const;
            r1_function_type r1_function_value( &::SireMM::MovingHarmonicRestraint::r1 );
            
            MovingHarmonicRestraint_exposer.def( 
                "r1"
                , r1_function_value
                , bp::release_gil_policy()
                , "Return the dissociation energy (depth) of MovingHarmonic bond" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::toString
        
            typedef ::QString ( ::SireMM::MovingHarmonicRestraint::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::MovingHarmonicRestraint::toString );
            
            MovingHarmonicRestraint_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::MovingHarmonicRestraint::typeName );
            
            MovingHarmonicRestraint_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraint::what
        
            typedef char const * ( ::SireMM::MovingHarmonicRestraint::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::MovingHarmonicRestraint::what );
            
            MovingHarmonicRestraint_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        MovingHarmonicRestraint_exposer.staticmethod( "typeName" );
        MovingHarmonicRestraint_exposer.def( "__copy__", &__copy__<SireMM::MovingHarmonicRestraint>);
        MovingHarmonicRestraint_exposer.def( "__deepcopy__", &__copy__<SireMM::MovingHarmonicRestraint>);
        MovingHarmonicRestraint_exposer.def( "clone", &__copy__<SireMM::MovingHarmonicRestraint>);
        MovingHarmonicRestraint_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::MovingHarmonicRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        MovingHarmonicRestraint_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::MovingHarmonicRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        MovingHarmonicRestraint_exposer.def_pickle(sire_pickle_suite< ::SireMM::MovingHarmonicRestraint >());
        MovingHarmonicRestraint_exposer.def( "__str__", &__str__< ::SireMM::MovingHarmonicRestraint > );
        MovingHarmonicRestraint_exposer.def( "__repr__", &__str__< ::SireMM::MovingHarmonicRestraint > );
    }

}
