// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MovingHarmonicRestraints_hpp__pyplusplus_wrapper
#define MovingHarmonicRestraints_hpp__pyplusplus_wrapper

void register_MovingHarmonicRestraints_class();

#endif//MovingHarmonicRestraints_hpp__pyplusplus_wrapper
