// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "Helpers/clone_const_reference.hpp"
#include "MovingHarmonicRestraints.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "movingharmonicrestraints.h"

#include <QDebug>

#include "movingharmonicrestraints.h"

SireMM::MovingHarmonicRestraints __copy__(const SireMM::MovingHarmonicRestraints &other){ return SireMM::MovingHarmonicRestraints(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

#include "Helpers/len.hpp"

void register_MovingHarmonicRestraints_class(){

    { //::SireMM::MovingHarmonicRestraints
        typedef bp::class_< SireMM::MovingHarmonicRestraints, bp::bases< SireMM::Restraints, SireBase::Property > > MovingHarmonicRestraints_exposer_t;
        MovingHarmonicRestraints_exposer_t MovingHarmonicRestraints_exposer = MovingHarmonicRestraints_exposer_t( "MovingHarmonicRestraints", "This class provides the information for a collection of Moving Harmonic Restraints\nrestraints that can be added to a collection of molecues. Each\nrestraint can act on a pair of particles or a pair of the\ncentroids of two collections of particles.\nThe restaints are spherically symmetric, and\nare simple harmonic potentials\n", bp::init< >("Null constructor") );
        bp::scope MovingHarmonicRestraints_scope( MovingHarmonicRestraints_exposer );
        MovingHarmonicRestraints_exposer.def( bp::init< QString const & >(( bp::arg("name") ), "") );
        MovingHarmonicRestraints_exposer.def( bp::init< SireMM::MovingHarmonicRestraint const & >(( bp::arg("restraint") ), "") );
        MovingHarmonicRestraints_exposer.def( bp::init< QList< SireMM::MovingHarmonicRestraint > const & >(( bp::arg("restraints") ), "") );
        MovingHarmonicRestraints_exposer.def( bp::init< QString const &, SireMM::MovingHarmonicRestraint const & >(( bp::arg("name"), bp::arg("restraint") ), "") );
        MovingHarmonicRestraints_exposer.def( bp::init< QString const &, QList< SireMM::MovingHarmonicRestraint > const & >(( bp::arg("name"), bp::arg("restraints") ), "") );
        MovingHarmonicRestraints_exposer.def( bp::init< SireMM::MovingHarmonicRestraints const & >(( bp::arg("other") ), "") );
        { //::SireMM::MovingHarmonicRestraints::add
        
            typedef void ( ::SireMM::MovingHarmonicRestraints::*add_function_type)( ::SireMM::MovingHarmonicRestraint const & ) ;
            add_function_type add_function_value( &::SireMM::MovingHarmonicRestraints::add );
            
            MovingHarmonicRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraint") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::add
        
            typedef void ( ::SireMM::MovingHarmonicRestraints::*add_function_type)( ::SireMM::MovingHarmonicRestraints const & ) ;
            add_function_type add_function_value( &::SireMM::MovingHarmonicRestraints::add );
            
            MovingHarmonicRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraints") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::at
        
            typedef ::SireMM::MovingHarmonicRestraint const & ( ::SireMM::MovingHarmonicRestraints::*at_function_type)( int ) const;
            at_function_type at_function_value( &::SireMM::MovingHarmonicRestraints::at );
            
            MovingHarmonicRestraints_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "Return the ith restraint" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::atomRestraints
        
            typedef ::QList< SireMM::MovingHarmonicRestraint > ( ::SireMM::MovingHarmonicRestraints::*atomRestraints_function_type)(  ) const;
            atomRestraints_function_type atomRestraints_function_value( &::SireMM::MovingHarmonicRestraints::atomRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "atomRestraints"
                , atomRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the atom restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::centroidRestraints
        
            typedef ::QList< SireMM::MovingHarmonicRestraint > ( ::SireMM::MovingHarmonicRestraints::*centroidRestraints_function_type)(  ) const;
            centroidRestraints_function_type centroidRestraints_function_value( &::SireMM::MovingHarmonicRestraints::centroidRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "centroidRestraints"
                , centroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the centroid restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::count
        
            typedef int ( ::SireMM::MovingHarmonicRestraints::*count_function_type)(  ) const;
            count_function_type count_function_value( &::SireMM::MovingHarmonicRestraints::count );
            
            MovingHarmonicRestraints_exposer.def( 
                "count"
                , count_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::hasAtomRestraints
        
            typedef bool ( ::SireMM::MovingHarmonicRestraints::*hasAtomRestraints_function_type)(  ) const;
            hasAtomRestraints_function_type hasAtomRestraints_function_value( &::SireMM::MovingHarmonicRestraints::hasAtomRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "hasAtomRestraints"
                , hasAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any atom restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::hasCentroidRestraints
        
            typedef bool ( ::SireMM::MovingHarmonicRestraints::*hasCentroidRestraints_function_type)(  ) const;
            hasCentroidRestraints_function_type hasCentroidRestraints_function_value( &::SireMM::MovingHarmonicRestraints::hasCentroidRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "hasCentroidRestraints"
                , hasCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any centroid restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::isEmpty
        
            typedef bool ( ::SireMM::MovingHarmonicRestraints::*isEmpty_function_type)(  ) const;
            isEmpty_function_type isEmpty_function_value( &::SireMM::MovingHarmonicRestraints::isEmpty );
            
            MovingHarmonicRestraints_exposer.def( 
                "isEmpty"
                , isEmpty_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::isNull
        
            typedef bool ( ::SireMM::MovingHarmonicRestraints::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::MovingHarmonicRestraints::isNull );
            
            MovingHarmonicRestraints_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::nAtomRestraints
        
            typedef int ( ::SireMM::MovingHarmonicRestraints::*nAtomRestraints_function_type)(  ) const;
            nAtomRestraints_function_type nAtomRestraints_function_value( &::SireMM::MovingHarmonicRestraints::nAtomRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "nAtomRestraints"
                , nAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of atom restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::nCentroidRestraints
        
            typedef int ( ::SireMM::MovingHarmonicRestraints::*nCentroidRestraints_function_type)(  ) const;
            nCentroidRestraints_function_type nCentroidRestraints_function_value( &::SireMM::MovingHarmonicRestraints::nCentroidRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "nCentroidRestraints"
                , nCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of centroid restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::nRestraints
        
            typedef int ( ::SireMM::MovingHarmonicRestraints::*nRestraints_function_type)(  ) const;
            nRestraints_function_type nRestraints_function_value( &::SireMM::MovingHarmonicRestraints::nRestraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "nRestraints"
                , nRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        MovingHarmonicRestraints_exposer.def( bp::self != bp::self );
        MovingHarmonicRestraints_exposer.def( bp::self + bp::other< SireMM::MovingHarmonicRestraint >() );
        MovingHarmonicRestraints_exposer.def( bp::self + bp::self );
        { //::SireMM::MovingHarmonicRestraints::operator=
        
            typedef ::SireMM::MovingHarmonicRestraints & ( ::SireMM::MovingHarmonicRestraints::*assign_function_type)( ::SireMM::MovingHarmonicRestraints const & ) ;
            assign_function_type assign_function_value( &::SireMM::MovingHarmonicRestraints::operator= );
            
            MovingHarmonicRestraints_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        MovingHarmonicRestraints_exposer.def( bp::self == bp::self );
        { //::SireMM::MovingHarmonicRestraints::operator[]
        
            typedef ::SireMM::MovingHarmonicRestraint const & ( ::SireMM::MovingHarmonicRestraints::*__getitem___function_type)( int ) const;
            __getitem___function_type __getitem___function_value( &::SireMM::MovingHarmonicRestraints::operator[] );
            
            MovingHarmonicRestraints_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::restraints
        
            typedef ::QList< SireMM::MovingHarmonicRestraint > ( ::SireMM::MovingHarmonicRestraints::*restraints_function_type)(  ) const;
            restraints_function_type restraints_function_value( &::SireMM::MovingHarmonicRestraints::restraints );
            
            MovingHarmonicRestraints_exposer.def( 
                "restraints"
                , restraints_function_value
                , bp::release_gil_policy()
                , "Return all of the restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::size
        
            typedef int ( ::SireMM::MovingHarmonicRestraints::*size_function_type)(  ) const;
            size_function_type size_function_value( &::SireMM::MovingHarmonicRestraints::size );
            
            MovingHarmonicRestraints_exposer.def( 
                "size"
                , size_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::toString
        
            typedef ::QString ( ::SireMM::MovingHarmonicRestraints::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::MovingHarmonicRestraints::toString );
            
            MovingHarmonicRestraints_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::MovingHarmonicRestraints::typeName );
            
            MovingHarmonicRestraints_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::MovingHarmonicRestraints::what
        
            typedef char const * ( ::SireMM::MovingHarmonicRestraints::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::MovingHarmonicRestraints::what );
            
            MovingHarmonicRestraints_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        MovingHarmonicRestraints_exposer.staticmethod( "typeName" );
        MovingHarmonicRestraints_exposer.def( "__copy__", &__copy__<SireMM::MovingHarmonicRestraints>);
        MovingHarmonicRestraints_exposer.def( "__deepcopy__", &__copy__<SireMM::MovingHarmonicRestraints>);
        MovingHarmonicRestraints_exposer.def( "clone", &__copy__<SireMM::MovingHarmonicRestraints>);
        MovingHarmonicRestraints_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::MovingHarmonicRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        MovingHarmonicRestraints_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::MovingHarmonicRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        MovingHarmonicRestraints_exposer.def_pickle(sire_pickle_suite< ::SireMM::MovingHarmonicRestraints >());
        MovingHarmonicRestraints_exposer.def( "__str__", &__str__< ::SireMM::MovingHarmonicRestraints > );
        MovingHarmonicRestraints_exposer.def( "__repr__", &__str__< ::SireMM::MovingHarmonicRestraints > );
        MovingHarmonicRestraints_exposer.def( "__len__", &__len_size< ::SireMM::MovingHarmonicRestraints > );
    }

}
