// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "Helpers/clone_const_reference.hpp"
#include "SoftAngleRestraints.pypp.hpp"

namespace bp = boost::python;

#include "SireCAS/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "softanglerestraints.h"

#include <QDebug>

#include "softanglerestraints.h"

SireMM::SoftAngleRestraints __copy__(const SireMM::SoftAngleRestraints &other){ return SireMM::SoftAngleRestraints(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

#include "Helpers/len.hpp"

void register_SoftAngleRestraints_class(){

    { //::SireMM::SoftAngleRestraints
        typedef bp::class_< SireMM::SoftAngleRestraints, bp::bases< SireMM::Restraints, SireBase::Property > > SoftAngleRestraints_exposer_t;
        SoftAngleRestraints_exposer_t SoftAngleRestraints_exposer = SoftAngleRestraints_exposer_t( "SoftAngleRestraints", "This class represents a collection of angle restraints", bp::init< >("Null constructor") );
        bp::scope SoftAngleRestraints_scope( SoftAngleRestraints_exposer );
        SoftAngleRestraints_exposer.def( bp::init< QString const & >(( bp::arg("name") ), "") );
        SoftAngleRestraints_exposer.def( bp::init< SireMM::SoftAngleRestraint const & >(( bp::arg("restraint") ), "") );
        SoftAngleRestraints_exposer.def( bp::init< QList< SireMM::SoftAngleRestraint > const & >(( bp::arg("restraints") ), "") );
        SoftAngleRestraints_exposer.def( bp::init< QString const &, SireMM::SoftAngleRestraint const & >(( bp::arg("name"), bp::arg("restraint") ), "") );
        SoftAngleRestraints_exposer.def( bp::init< QString const &, QList< SireMM::SoftAngleRestraint > const & >(( bp::arg("name"), bp::arg("restraints") ), "") );
        SoftAngleRestraints_exposer.def( bp::init< SireMM::SoftAngleRestraints const & >(( bp::arg("other") ), "") );
        { //::SireMM::SoftAngleRestraints::add
        
            typedef void ( ::SireMM::SoftAngleRestraints::*add_function_type)( ::SireMM::SoftAngleRestraint const & ) ;
            add_function_type add_function_value( &::SireMM::SoftAngleRestraints::add );
            
            SoftAngleRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraint") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::SoftAngleRestraints::add
        
            typedef void ( ::SireMM::SoftAngleRestraints::*add_function_type)( ::SireMM::SoftAngleRestraints const & ) ;
            add_function_type add_function_value( &::SireMM::SoftAngleRestraints::add );
            
            SoftAngleRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraints") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::SoftAngleRestraints::at
        
            typedef ::SireMM::SoftAngleRestraint const & ( ::SireMM::SoftAngleRestraints::*at_function_type)( int ) const;
            at_function_type at_function_value( &::SireMM::SoftAngleRestraints::at );
            
            SoftAngleRestraints_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "Return the ith restraint" );
        
        }
        { //::SireMM::SoftAngleRestraints::count
        
            typedef int ( ::SireMM::SoftAngleRestraints::*count_function_type)(  ) const;
            count_function_type count_function_value( &::SireMM::SoftAngleRestraints::count );
            
            SoftAngleRestraints_exposer.def( 
                "count"
                , count_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::SoftAngleRestraints::isEmpty
        
            typedef bool ( ::SireMM::SoftAngleRestraints::*isEmpty_function_type)(  ) const;
            isEmpty_function_type isEmpty_function_value( &::SireMM::SoftAngleRestraints::isEmpty );
            
            SoftAngleRestraints_exposer.def( 
                "isEmpty"
                , isEmpty_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::SoftAngleRestraints::isNull
        
            typedef bool ( ::SireMM::SoftAngleRestraints::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::SoftAngleRestraints::isNull );
            
            SoftAngleRestraints_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::SoftAngleRestraints::nRestraints
        
            typedef int ( ::SireMM::SoftAngleRestraints::*nRestraints_function_type)(  ) const;
            nRestraints_function_type nRestraints_function_value( &::SireMM::SoftAngleRestraints::nRestraints );
            
            SoftAngleRestraints_exposer.def( 
                "nRestraints"
                , nRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        SoftAngleRestraints_exposer.def( bp::self != bp::self );
        SoftAngleRestraints_exposer.def( bp::self + bp::other< SireMM::SoftAngleRestraint >() );
        SoftAngleRestraints_exposer.def( bp::self + bp::self );
        { //::SireMM::SoftAngleRestraints::operator=
        
            typedef ::SireMM::SoftAngleRestraints & ( ::SireMM::SoftAngleRestraints::*assign_function_type)( ::SireMM::SoftAngleRestraints const & ) ;
            assign_function_type assign_function_value( &::SireMM::SoftAngleRestraints::operator= );
            
            SoftAngleRestraints_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        SoftAngleRestraints_exposer.def( bp::self == bp::self );
        { //::SireMM::SoftAngleRestraints::operator[]
        
            typedef ::SireMM::SoftAngleRestraint const & ( ::SireMM::SoftAngleRestraints::*__getitem___function_type)( int ) const;
            __getitem___function_type __getitem___function_value( &::SireMM::SoftAngleRestraints::operator[] );
            
            SoftAngleRestraints_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraints::restraints
        
            typedef ::QList< SireMM::SoftAngleRestraint > ( ::SireMM::SoftAngleRestraints::*restraints_function_type)(  ) const;
            restraints_function_type restraints_function_value( &::SireMM::SoftAngleRestraints::restraints );
            
            SoftAngleRestraints_exposer.def( 
                "restraints"
                , restraints_function_value
                , bp::release_gil_policy()
                , "Return all of the restraints" );
        
        }
        { //::SireMM::SoftAngleRestraints::size
        
            typedef int ( ::SireMM::SoftAngleRestraints::*size_function_type)(  ) const;
            size_function_type size_function_value( &::SireMM::SoftAngleRestraints::size );
            
            SoftAngleRestraints_exposer.def( 
                "size"
                , size_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::SoftAngleRestraints::toString
        
            typedef ::QString ( ::SireMM::SoftAngleRestraints::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::SoftAngleRestraints::toString );
            
            SoftAngleRestraints_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraints::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::SoftAngleRestraints::typeName );
            
            SoftAngleRestraints_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraints::what
        
            typedef char const * ( ::SireMM::SoftAngleRestraints::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::SoftAngleRestraints::what );
            
            SoftAngleRestraints_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        SoftAngleRestraints_exposer.staticmethod( "typeName" );
        SoftAngleRestraints_exposer.def( "__copy__", &__copy__<SireMM::SoftAngleRestraints>);
        SoftAngleRestraints_exposer.def( "__deepcopy__", &__copy__<SireMM::SoftAngleRestraints>);
        SoftAngleRestraints_exposer.def( "clone", &__copy__<SireMM::SoftAngleRestraints>);
        SoftAngleRestraints_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::SoftAngleRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        SoftAngleRestraints_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::SoftAngleRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        SoftAngleRestraints_exposer.def_pickle(sire_pickle_suite< ::SireMM::SoftAngleRestraints >());
        SoftAngleRestraints_exposer.def( "__str__", &__str__< ::SireMM::SoftAngleRestraints > );
        SoftAngleRestraints_exposer.def( "__repr__", &__str__< ::SireMM::SoftAngleRestraints > );
        SoftAngleRestraints_exposer.def( "__len__", &__len_size< ::SireMM::SoftAngleRestraints > );
    }

}
