// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "SoftAngleRestraint.pypp.hpp"

namespace bp = boost::python;

#include "SireCAS/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "softanglerestraints.h"

#include <QDebug>

#include "softanglerestraints.h"

SireMM::SoftAngleRestraint __copy__(const SireMM::SoftAngleRestraint &other){ return SireMM::SoftAngleRestraint(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

void register_SoftAngleRestraint_class(){

    { //::SireMM::SoftAngleRestraint
        typedef bp::class_< SireMM::SoftAngleRestraint, bp::bases< SireBase::Property > > SoftAngleRestraint_exposer_t;
        SoftAngleRestraint_exposer_t SoftAngleRestraint_exposer = SoftAngleRestraint_exposer_t( "SoftAngleRestraint", "This class represents a single angle restraint between any three\natoms in a system softened by a plateau potential.\nAuthor: Audrius Kalpokas\n", bp::init< >("Null constructor") );
        bp::scope SoftAngleRestraint_scope( SoftAngleRestraint_exposer );
        SoftAngleRestraint_exposer.def( bp::init< QList< long long > const &, SireUnits::Dimension::Angle const &, SireUnits::Dimension::HarmonicAngleConstant const &, SireUnits::Dimension::MolarEnergy const & >(( bp::arg("atoms"), bp::arg("theta0"), bp::arg("ktheta"), bp::arg("pe") ), "Construct a restraint that acts on the angle within the\nthree atoms atom0, atom1 and atom2 (theta == a(012)),\nrestraining the angle within these atoms") );
        SoftAngleRestraint_exposer.def( bp::init< SireMM::SoftAngleRestraint const & >(( bp::arg("other") ), "Copy constructor") );
        { //::SireMM::SoftAngleRestraint::atoms
        
            typedef ::QVector< long long > ( ::SireMM::SoftAngleRestraint::*atoms_function_type)(  ) const;
            atoms_function_type atoms_function_value( &::SireMM::SoftAngleRestraint::atoms );
            
            SoftAngleRestraint_exposer.def( 
                "atoms"
                , atoms_function_value
                , bp::release_gil_policy()
                , "Return the atoms involved in the restraint" );
        
        }
        { //::SireMM::SoftAngleRestraint::isNull
        
            typedef bool ( ::SireMM::SoftAngleRestraint::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::SoftAngleRestraint::isNull );
            
            SoftAngleRestraint_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraint::ktheta
        
            typedef ::SireUnits::Dimension::HarmonicAngleConstant ( ::SireMM::SoftAngleRestraint::*ktheta_function_type)(  ) const;
            ktheta_function_type ktheta_function_value( &::SireMM::SoftAngleRestraint::ktheta );
            
            SoftAngleRestraint_exposer.def( 
                "ktheta"
                , ktheta_function_value
                , bp::release_gil_policy()
                , "Return the force constant for the restraint" );
        
        }
        SoftAngleRestraint_exposer.def( bp::self != bp::self );
        SoftAngleRestraint_exposer.def( bp::self + bp::self );
        SoftAngleRestraint_exposer.def( bp::self + bp::other< SireMM::SoftAngleRestraints >() );
        { //::SireMM::SoftAngleRestraint::operator=
        
            typedef ::SireMM::SoftAngleRestraint & ( ::SireMM::SoftAngleRestraint::*assign_function_type)( ::SireMM::SoftAngleRestraint const & ) ;
            assign_function_type assign_function_value( &::SireMM::SoftAngleRestraint::operator= );
            
            SoftAngleRestraint_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        SoftAngleRestraint_exposer.def( bp::self == bp::self );
        { //::SireMM::SoftAngleRestraint::pe
        
            typedef ::SireUnits::Dimension::MolarEnergy ( ::SireMM::SoftAngleRestraint::*pe_function_type)(  ) const;
            pe_function_type pe_function_value( &::SireMM::SoftAngleRestraint::pe );
            
            SoftAngleRestraint_exposer.def( 
                "pe"
                , pe_function_value
                , bp::release_gil_policy()
                , "Return the plateau energy of the restraint" );
        
        }
        { //::SireMM::SoftAngleRestraint::theta0
        
            typedef ::SireUnits::Dimension::Angle ( ::SireMM::SoftAngleRestraint::*theta0_function_type)(  ) const;
            theta0_function_type theta0_function_value( &::SireMM::SoftAngleRestraint::theta0 );
            
            SoftAngleRestraint_exposer.def( 
                "theta0"
                , theta0_function_value
                , bp::release_gil_policy()
                , "Return the equilibrium angle for the restraint" );
        
        }
        { //::SireMM::SoftAngleRestraint::toString
        
            typedef ::QString ( ::SireMM::SoftAngleRestraint::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::SoftAngleRestraint::toString );
            
            SoftAngleRestraint_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraint::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::SoftAngleRestraint::typeName );
            
            SoftAngleRestraint_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::SoftAngleRestraint::what
        
            typedef char const * ( ::SireMM::SoftAngleRestraint::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::SoftAngleRestraint::what );
            
            SoftAngleRestraint_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        SoftAngleRestraint_exposer.staticmethod( "typeName" );
        SoftAngleRestraint_exposer.def( "__copy__", &__copy__<SireMM::SoftAngleRestraint>);
        SoftAngleRestraint_exposer.def( "__deepcopy__", &__copy__<SireMM::SoftAngleRestraint>);
        SoftAngleRestraint_exposer.def( "clone", &__copy__<SireMM::SoftAngleRestraint>);
        SoftAngleRestraint_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::SoftAngleRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        SoftAngleRestraint_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::SoftAngleRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        SoftAngleRestraint_exposer.def_pickle(sire_pickle_suite< ::SireMM::SoftAngleRestraint >());
        SoftAngleRestraint_exposer.def( "__str__", &__str__< ::SireMM::SoftAngleRestraint > );
        SoftAngleRestraint_exposer.def( "__repr__", &__str__< ::SireMM::SoftAngleRestraint > );
    }

}
