// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SoftAngleRestraint_hpp__pyplusplus_wrapper
#define SoftAngleRestraint_hpp__pyplusplus_wrapper

void register_SoftAngleRestraint_class();

#endif//SoftAngleRestraint_hpp__pyplusplus_wrapper
