// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SoftAngleRestraints_hpp__pyplusplus_wrapper
#define SoftAngleRestraints_hpp__pyplusplus_wrapper

void register_SoftAngleRestraints_class();

#endif//SoftAngleRestraints_hpp__pyplusplus_wrapper
